//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class chucvu
    {
        public int id { get; set; }
        public string chuc_vu { get; set; }
        public float he_so { get; set; }
    }
}
