//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngach
    {
        public int id { get; set; }
        public string maso { get; set; }
        public string ngach1 { get; set; }
        public int nien_hang { get; set; }
        public string C_1 { get; set; }
        public string C_2 { get; set; }
        public string C_3 { get; set; }
        public string C_4 { get; set; }
        public string C_5 { get; set; }
        public string C_6 { get; set; }
        public string C_7 { get; set; }
        public string C_8 { get; set; }
    }
}
