//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien_ngach
    {
        public int id { get; set; }
        public int id_ngach { get; set; }
        public int id_nhanvien { get; set; }
        public string bac { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    }
}
