//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public int id { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string gioi_tinh { get; set; }
        public string ngay_sinh { get; set; }
        public string dan_toc { get; set; }
        public string ngay_vao_lam { get; set; }
        public string dia_chi { get; set; }
        public string so_cmnd { get; set; }
    }
}
