//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salaryContext : DbContext
    {
        public salaryContext()
            : base("name=salaryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chucvu> chucvu { get; set; }
        public virtual DbSet<ngach> ngach { get; set; }
        public virtual DbSet<nhanvien> nhanvien { get; set; }
        public virtual DbSet<nhanvien_chucvu> nhanvien_chucvu { get; set; }
        public virtual DbSet<nhanvien_ngach> nhanvien_ngach { get; set; }
        public virtual DbSet<luong> luong { get; set; }
    }
}
